name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-std:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test --no-fail-fast

  test-no-std:
    name: "Tests (no std)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests (no std)
        run: cargo test -p portable-hash --lib --tests --no-default-features --no-fail-fast

  test-msrv:
    name: "Tests (MSRV ${{ matrix.rust_version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # We test the MSRV for the version before and on every rustversion gate that we have in the
        # codebase to ensure that each version boundary is covered. It's unnecessary to test
        # absolutely all releases! Remember to add new versions if we add more boundaries.
        rust_version:
          - 1.57.0  # MSRV
          - 1.63.0
          - 1.64.0  # CStr and CString stabilised
          - 1.73.0
          - 1.74.0  # Saturating stabilised
          - 1.77.0
          - 1.78.0  # Ptr<T> impl using associated generics
          - stable
          - nightly
    env:
      RUST_VERSION: ${{ matrix.rust_version }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Install Rust (rustup, ${{ env.RUST_VERSION }})
        shell: bash
        run: |
          set -euo pipefail
          rustup update ${{ env.RUST_VERSION }} --no-self-update
          rustup default ${{ env.RUST_VERSION }}
          cargo -V
          rustc -V
      - name: Pin MSRV-compatible dependency versions
        run: |
          cargo update -p proc-macro2 --precise 1.0.95
          cargo update -p quote --precise 1.0.40
          cargo update -p syn --precise 2.0.56
          cargo update -p unicode-ident --precise 1.0.18
      - name: Test portable-hash (no_std)
        run: cargo test -p portable-hash --lib --tests --no-default-features --no-fail-fast
      - name: Test sha-hasher portability
        if: matrix.rust_version != '1.57.0'
        run: cargo test -p sha-hasher --lib --tests --all-features --no-fail-fast
